language: python
python:
  - 3.6
install:
  - pip install -r dev_requirements.txt
script:
  - coverage run setup.py test_on_postgres
  - flake8 .
after_success:
  coveralls
notifications:
  email:
  - ci-notify@fulfil.io
